"""
NasriTools Product Catalog
Each entry is a full product config ready for factory.build_product()
"""

CATALOG = [

    # ─── 1. Personal Budget Tracker ──────────────────────────────────
    {
        "slug": "budget_tracker",
        "name": "Personal Budget Tracker",
        "subtitle": "Monthly & Annual Finance Google Sheets Template",
        "price": "$12",
        "listing_title": "Personal Budget Tracker Google Sheets | Monthly Budget Planner | Expense Tracker Spreadsheet",
        "listing_emoji": "💰",
        "category": "Craft Supplies & Tools → Templates → Spreadsheets",
        "description_intro": "Take full control of your money with this powerful yet simple budget tracker. Know exactly where every dollar goes.",
        "accent_color": "4361EE",
        "dark_color": "0D1B2A",
        "green_color": "06D6A0",
        "yellow_color": "FFD166",
        "red_color": "EF233C",
        "kpis_preview": ["Income", "Expenses", "Savings", "Balance"],
        "tabs": [
            {"name": "Dashboard",     "emoji": "🏠", "color": "0D1B2A", "type": "dashboard",
             "description": "Monthly overview: income, expenses, savings rate.",
             "kpis": [
                 {"label": "Income",   "formula": "=SUM(Income!B:B)"},
                 {"label": "Expenses", "formula": "=SUM(Expenses!D:D)"},
                 {"label": "Savings",  "formula": "=B4-C4"},
                 {"label": "Rate",     "formula": '=TEXT(D4/B4,"0%")'},
             ]},
            {"name": "Income",        "emoji": "💵", "color": "06D6A0", "type": "table",
             "description": "Log all income with date, source, category, and amount.",
             "columns": [
                 {"name": "Date",     "width": 14, "sample": "2024-01-01"},
                 {"name": "Amount",   "width": 14, "sample": "3000"},
                 {"name": "Source",   "width": 20, "sample": "Salary"},
                 {"name": "Category", "width": 18, "dropdown": ["Salary","Freelance","Business","Investment","Other"]},
                 {"name": "Notes",    "width": 26, "sample": "Monthly salary"},
             ], "sample_rows": 8},
            {"name": "Expenses",      "emoji": "💳", "color": "EF233C", "type": "table",
             "description": "Track all expenses vs budget with auto red alert when over.",
             "columns": [
                 {"name": "Date",     "width": 14, "sample": "2024-01-05"},
                 {"name": "Item",     "width": 22, "sample": "Rent"},
                 {"name": "Category", "width": 18, "dropdown": ["Housing","Food","Transport","Health","Entertainment","Savings","Other"]},
                 {"name": "Amount",   "width": 14, "sample": "800"},
                 {"name": "Budget",   "width": 14, "sample": "850"},
                 {"name": "Notes",    "width": 22, "sample": "Monthly rent"},
             ], "sample_rows": 12},
            {"name": "Savings Goals", "emoji": "🎯", "color": "4361EE", "type": "table",
             "description": "Set savings goals and auto-track progress percentage.",
             "columns": [
                 {"name": "Goal",     "width": 24, "sample": "Emergency Fund"},
                 {"name": "Target",   "width": 14, "sample": "5000"},
                 {"name": "Saved",    "width": 14, "sample": "1200"},
                 {"name": "Progress", "width": 14, "formula": '=TEXT(D{ROW}/C{ROW},"0%")'},
                 {"name": "Deadline", "width": 16, "sample": "2024-12-31"},
             ], "sample_rows": 5},
            {"name": "Monthly View",  "emoji": "📅", "color": "9B59B6", "type": "table",
             "description": "Month-by-month income vs expenses trend.",
             "columns": [
                 {"name": "Month",    "width": 16, "sample": "January 2024"},
                 {"name": "Income",   "width": 14, "sample": "3000"},
                 {"name": "Expenses", "width": 14, "sample": "2100"},
                 {"name": "Savings",  "width": 14, "formula": "=C{ROW}-D{ROW}"},
                 {"name": "Rate",     "width": 12, "formula": '=TEXT(E{ROW}/C{ROW},"0%")'},
             ], "sample_rows": 12},
            {"name": "Reports",       "emoji": "📊", "color": "E67E22", "type": "reports",
             "description": "Annual totals, savings trend, top expense categories.",
             "sections": [
                 {"title": "Annual Summary", "items": [
                     {"label": "Total Income",   "formula": "=SUM(Income!B:B)"},
                     {"label": "Total Expenses", "formula": "=SUM(Expenses!D:D)"},
                     {"label": "Total Savings",  "formula": "=SUM(Income!B:B)-SUM(Expenses!D:D)"},
                 ]},
             ]},
        ],
        "features": [
            "Auto savings rate calculation",
            "Budget vs Actual (turns red when over budget)",
            "12-month comparison view",
            "Savings goals with progress tracking",
            "Income & expense categorization",
            "Annual totals auto-calculated",
            "No subscriptions — yours forever",
            "Works in Google Sheets & Excel",
        ],
        "perfect_for": [
            "Anyone wanting to control monthly spending",
            "People saving for a house, car, or trip",
            "Freelancers with variable income",
            "Families managing household budgets",
            "Students budgeting for the first time",
            "Anyone tired of expensive budgeting apps",
        ],
        "how_to_use": [
            "Purchase & download the .xlsx file instantly",
            "Open in Google Sheets or Excel",
            "Fill YELLOW cells with your income and expenses",
            "Dashboard shows your financial picture automatically",
        ],
        "tips": [
            "Update expenses daily for best accuracy.",
            "Set a savings goal first — it motivates consistent tracking.",
            "Duplicate the file each year for annual archives.",
            "Change the tax rate cell if needed for your country.",
        ],
        "tags": [
            "budget tracker google sheets",
            "monthly budget template",
            "personal finance spreadsheet",
            "expense tracker excel",
            "savings goal tracker",
            "budget planner template",
            "household budget sheet",
            "income expense tracker",
            "financial planner google",
            "money management template",
            "monthly expenses sheet",
            "budget spreadsheet instant",
            "personal budget tracker",
        ],
    },

    # ─── 2. Content Creator Planner ──────────────────────────────────
    {
        "slug": "content_creator_planner",
        "name": "Content Creator Planner",
        "subtitle": "Social Media & YouTube Google Sheets Template",
        "price": "$15",
        "listing_title": "Content Creator Planner Google Sheets | YouTube Instagram TikTok Content Calendar Template",
        "listing_emoji": "🎬",
        "category": "Craft Supplies & Tools → Templates → Spreadsheets",
        "description_intro": "Plan, track, and grow your content empire across ALL platforms from one spreadsheet.",
        "accent_color": "E91E8C",
        "dark_color": "0D1B2A",
        "green_color": "00BCD4",
        "yellow_color": "FFD166",
        "red_color": "EF233C",
        "kpis_preview": ["Videos", "Views", "Subs", "Revenue"],
        "tabs": [
            {"name": "Dashboard",      "emoji": "🏠", "color": "0D1B2A", "type": "dashboard",
             "description": "Channel overview: total videos, views, subscribers, estimated revenue.",
             "kpis": [
                 {"label": "Total Videos",  "formula": "=COUNTA(Content!A:A)-1"},
                 {"label": "Total Views",   "formula": "=SUM(Analytics!C:C)"},
                 {"label": "Avg Views",     "formula": "=IFERROR(B4/A4,0)"},
                 {"label": "Est. Revenue",  "formula": "=SUM(Analytics!E:E)"},
             ]},
            {"name": "Content Calendar","emoji": "📅", "color": "E91E8C", "type": "table",
             "description": "Plan videos/posts by date, platform, status, and topic.",
             "columns": [
                 {"name": "Publish Date", "width": 16, "sample": "2024-01-15"},
                 {"name": "Platform",     "width": 16, "dropdown": ["YouTube","Instagram","TikTok","Twitter/X","LinkedIn","Blog","Pinterest"]},
                 {"name": "Title / Idea", "width": 34, "sample": "10 Tips for Better Productivity"},
                 {"name": "Status",       "width": 16, "dropdown": ["Idea","Scripting","Filming","Editing","Scheduled","Published"]},
                 {"name": "Tags / Notes", "width": 26, "sample": "productivity, tips"},
             ], "sample_rows": 15},
            {"name": "Content",        "emoji": "🎬", "color": "4361EE", "type": "table",
             "description": "Library of all published content with links and performance.",
             "columns": [
                 {"name": "Date",       "width": 14, "sample": "2024-01-15"},
                 {"name": "Platform",   "width": 14, "dropdown": ["YouTube","Instagram","TikTok","Twitter/X","LinkedIn","Blog"]},
                 {"name": "Title",      "width": 34, "sample": "My Best Video"},
                 {"name": "URL",        "width": 30, "sample": "youtube.com/watch?v=..."},
                 {"name": "Category",   "width": 18, "dropdown": ["Tutorial","Vlog","Review","Short","Podcast","Other"]},
             ], "sample_rows": 10},
            {"name": "Analytics",      "emoji": "📊", "color": "06D6A0", "type": "table",
             "description": "Track views, likes, comments, and estimated revenue per video.",
             "columns": [
                 {"name": "Video Title", "width": 32, "sample": "My Best Video"},
                 {"name": "Date",        "width": 14, "sample": "2024-01-15"},
                 {"name": "Views",       "width": 12, "sample": "1250"},
                 {"name": "Likes",       "width": 10, "sample": "87"},
                 {"name": "Revenue $",   "width": 12, "sample": "3.50"},
                 {"name": "CTR %",       "width": 10, "sample": "4.2"},
             ], "sample_rows": 10},
            {"name": "Ideas Bank",     "emoji": "💡", "color": "FFD166", "type": "table",
             "description": "Dump all your content ideas here with priority and keywords.",
             "columns": [
                 {"name": "Idea",        "width": 36, "sample": "How I grew 1000 subs"},
                 {"name": "Platform",    "width": 14, "dropdown": ["YouTube","Instagram","TikTok","Blog","Any"]},
                 {"name": "Priority",    "width": 12, "dropdown": ["🔥 Hot","Normal","Later","Archive"]},
                 {"name": "Keywords",    "width": 28, "sample": "growth, youtube, subscribers"},
             ], "sample_rows": 10},
            {"name": "Brand Deals",    "emoji": "💼", "color": "9B59B6", "type": "table",
             "description": "Track sponsorships, rates, deadlines, and payment status.",
             "columns": [
                 {"name": "Brand",       "width": 20, "sample": "Acme Corp"},
                 {"name": "Type",        "width": 18, "dropdown": ["Sponsored Video","Affiliate","Product Review","Shoutout","Long-term"]},
                 {"name": "Fee $",       "width": 12, "sample": "500"},
                 {"name": "Deadline",    "width": 14, "sample": "2024-02-01"},
                 {"name": "Status",      "width": 16, "dropdown": ["Negotiating","Confirmed","Delivered","Paid","Cancelled"]},
             ], "sample_rows": 5},
            {"name": "Reports",        "emoji": "📈", "color": "E67E22", "type": "reports",
             "description": "Monthly performance, top platforms, revenue totals.",
             "sections": [
                 {"title": "Performance Summary", "items": [
                     {"label": "Total Views",    "formula": "=SUM(Analytics!C:C)"},
                     {"label": "Total Revenue",  "formula": "=SUM(Analytics!E:E)"},
                     {"label": "Total Videos",   "formula": "=COUNTA(Content!A:A)-1"},
                 ]},
             ]},
        ],
        "features": [
            "Content calendar for ALL platforms in one place",
            "6 platform dropdowns (YouTube, Instagram, TikTok...)",
            "Analytics tracker with revenue estimation",
            "Ideas bank — never lose a content idea",
            "Brand deals tracker with payment status",
            "Color-coded content status (Idea → Published)",
            "Monthly performance reports auto-generated",
            "No subscriptions — yours forever",
        ],
        "perfect_for": [
            "YouTube creators growing their channel",
            "Instagram and TikTok content creators",
            "Multi-platform creators managing many accounts",
            "Bloggers and podcast hosts",
            "Freelance social media managers",
            "Anyone launching a content business",
        ],
        "how_to_use": [
            "Download and open in Google Sheets",
            "Add your content ideas to the Ideas Bank",
            "Schedule posts in the Content Calendar",
            "Log performance in Analytics — reports auto-update",
        ],
        "tips": [
            "Review your analytics every Monday for weekly planning.",
            "Batch-create content ideas on Sundays.",
            "Use the Ideas Bank dropdown filter to plan by platform.",
            "Track brand deal deadlines in the Brand Deals tab.",
        ],
        "tags": [
            "content creator planner",
            "youtube content calendar",
            "social media planner google",
            "content calendar template",
            "youtube planner spreadsheet",
            "instagram content planner",
            "tiktok content calendar",
            "content creator spreadsheet",
            "social media schedule sheet",
            "youtube analytics tracker",
            "brand deals tracker",
            "content ideas planner",
            "creator business template",
        ],
    },

    # ─── 3. Real Estate Deal Analyzer ────────────────────────────────
    {
        "slug": "real_estate_analyzer",
        "name": "Real Estate Deal Analyzer",
        "subtitle": "Investment Property Calculator Google Sheets",
        "price": "$22",
        "listing_title": "Real Estate Deal Analyzer Google Sheets | Rental Property ROI Calculator | Investment Spreadsheet",
        "listing_emoji": "🏠",
        "category": "Craft Supplies & Tools → Templates → Spreadsheets",
        "description_intro": "Analyze ANY rental property deal in minutes. Calculate ROI, cash flow, cap rate, and mortgage automatically.",
        "accent_color": "2ECC71",
        "dark_color": "1A2332",
        "green_color": "27AE60",
        "yellow_color": "F1C40F",
        "red_color": "E74C3C",
        "kpis_preview": ["Cash Flow", "ROI %", "Cap Rate", "GRM"],
        "tabs": [
            {"name": "Deal Analyzer",  "emoji": "🔍", "color": "2ECC71", "type": "dashboard",
             "description": "Input property details — all metrics calculate automatically.",
             "kpis": [
                 {"label": "Monthly Cash Flow", "formula": "=Income!B20-Expenses!B25"},
                 {"label": "Annual ROI %",      "formula": '=TEXT(B4*12/Financing!B15,"0.0%")'},
                 {"label": "Cap Rate",          "formula": '=TEXT((Income!B20-Expenses!B25)*12/Purchase!B5,"0.0%")'},
                 {"label": "GRM",               "formula": "=Purchase!B5/(Income!B20*12)"},
             ]},
            {"name": "Purchase Info",  "emoji": "🏡", "color": "1A2332", "type": "table",
             "description": "Enter purchase price, down payment, closing costs.",
             "columns": [
                 {"name": "Item",   "width": 30, "sample": "Purchase Price"},
                 {"name": "Value",  "width": 18, "sample": "250000"},
                 {"name": "Notes",  "width": 30, "sample": "Negotiated price"},
             ], "sample_rows": 8},
            {"name": "Income",         "emoji": "💵", "color": "2ECC71", "type": "table",
             "description": "Monthly rental income: rent, parking, laundry, vacancy adjustment.",
             "columns": [
                 {"name": "Income Source", "width": 28, "sample": "Monthly Rent"},
                 {"name": "Monthly $",     "width": 16, "sample": "1800"},
                 {"name": "Annual $",      "width": 16, "formula": "=C{ROW}*12"},
                 {"name": "Notes",         "width": 26, "sample": "Unit 1"},
             ], "sample_rows": 6},
            {"name": "Expenses",       "emoji": "💸", "color": "E74C3C", "type": "table",
             "description": "All expenses: mortgage, taxes, insurance, maintenance, management.",
             "columns": [
                 {"name": "Expense",    "width": 28, "sample": "Mortgage Payment"},
                 {"name": "Monthly $",  "width": 16, "sample": "900"},
                 {"name": "Annual $",   "width": 16, "formula": "=C{ROW}*12"},
                 {"name": "Category",   "width": 20, "dropdown": ["Fixed","Variable","One-time","Reserve"]},
             ], "sample_rows": 10},
            {"name": "Financing",      "emoji": "🏦", "color": "3498DB", "type": "table",
             "description": "Mortgage calculator: loan amount, rate, term, monthly payment.",
             "columns": [
                 {"name": "Item",   "width": 30, "sample": "Loan Amount"},
                 {"name": "Value",  "width": 18, "sample": "200000"},
                 {"name": "Notes",  "width": 30, "sample": "30-year fixed"},
             ], "sample_rows": 6},
            {"name": "Comparison",     "emoji": "⚖️", "color": "9B59B6", "type": "table",
             "description": "Compare up to 5 properties side by side on key metrics.",
             "columns": [
                 {"name": "Metric",      "width": 24, "sample": "Purchase Price"},
                 {"name": "Property 1",  "width": 16, "sample": "250000"},
                 {"name": "Property 2",  "width": 16, "sample": "320000"},
                 {"name": "Property 3",  "width": 16, "sample": "180000"},
                 {"name": "Best",        "width": 14, "formula": '=MIN(C{ROW}:E{ROW})'},
             ], "sample_rows": 8},
            {"name": "Reports",        "emoji": "📊", "color": "E67E22", "type": "reports",
             "description": "Full deal summary with all key investment metrics.",
             "sections": [
                 {"title": "Deal Summary", "items": [
                     {"label": "Monthly Cash Flow", "formula": "=Income!C20-Expenses!C25"},
                     {"label": "Annual Cash Flow",  "formula": "=(Income!C20-Expenses!C25)*12"},
                     {"label": "Total Investment",  "formula": "=SUM(Purchase!C:C)"},
                 ]},
             ]},
        ],
        "features": [
            "Complete ROI calculator (cash-on-cash, cap rate, GRM)",
            "Auto mortgage payment calculator",
            "Vacancy and management fee included",
            "Compare up to 3 properties side by side",
            "Monthly and annual cash flow breakdown",
            "All formulas pre-built — just enter numbers",
            "Works for rentals, flips, and commercial",
            "No expensive software needed",
        ],
        "perfect_for": [
            "Real estate investors analyzing deals",
            "First-time rental property buyers",
            "House flippers calculating profit margins",
            "Real estate agents advising investor clients",
            "Anyone comparing multiple investment properties",
            "BRRRR strategy investors",
        ],
        "how_to_use": [
            "Enter property details in Purchase Info tab",
            "Fill in rental income in the Income tab",
            "Add all expenses in the Expenses tab",
            "See ROI, cash flow, and cap rate auto-calculated",
        ],
        "tips": [
            "Always use conservative income estimates (90-95% occupancy).",
            "Add 10-15% of rent as maintenance reserve in expenses.",
            "Use the Comparison tab to rank multiple deals.",
            "Cap rate above 7% is generally considered good.",
        ],
        "tags": [
            "real estate analyzer spreadsheet",
            "rental property calculator",
            "investment property google sheets",
            "real estate roi calculator",
            "cash flow calculator rental",
            "cap rate calculator sheet",
            "property investment template",
            "rental income tracker",
            "house flip calculator",
            "real estate deal sheet",
            "mortgage calculator excel",
            "rental property analysis",
            "real estate spreadsheet",
        ],
    },

    # ─── 4. Student Planner ───────────────────────────────────────────
    {
        "slug": "student_planner",
        "name": "Ultimate Student Planner",
        "subtitle": "Semester, Grades & Study Schedule Google Sheets",
        "price": "$9",
        "listing_title": "Student Planner Google Sheets | Semester Planner Grade Tracker Study Schedule | Academic Planner",
        "listing_emoji": "📚",
        "category": "Craft Supplies & Tools → Templates → Spreadsheets",
        "description_intro": "Ace your semester with this all-in-one student planner. Track assignments, grades, study sessions, and goals — automatically.",
        "accent_color": "7C3AED",
        "dark_color": "1E1B4B",
        "green_color": "10B981",
        "yellow_color": "FBBF24",
        "red_color": "EF4444",
        "kpis_preview": ["GPA", "Assignments", "Study Hours", "Exams Left"],
        "tabs": [
            {"name": "Dashboard",      "emoji": "🏠", "color": "1E1B4B", "type": "dashboard",
             "description": "Semester overview: current GPA, pending assignments, upcoming exams.",
             "kpis": [
                 {"label": "Current GPA",      "formula": "=AVERAGE(Grades!D:D)"},
                 {"label": "Assignments Due",  "formula": "=COUNTIF(Assignments!D:D,\"Pending\")"},
                 {"label": "Study Hours",      "formula": "=SUM(Study!C:C)"},
                 {"label": "Exams Left",       "formula": "=COUNTIF(Exams!D:D,\"Upcoming\")"},
             ]},
            {"name": "Assignments",    "emoji": "📝", "color": "7C3AED", "type": "table",
             "description": "Track all assignments with due dates, status, and grades.",
             "columns": [
                 {"name": "Assignment",  "width": 30, "sample": "Essay: Chapter 5"},
                 {"name": "Subject",     "width": 18, "sample": "English"},
                 {"name": "Due Date",    "width": 14, "sample": "2024-02-10"},
                 {"name": "Status",      "width": 16, "dropdown": ["Pending","In Progress","Submitted","Graded","Late"]},
                 {"name": "Grade",       "width": 10, "sample": "85"},
                 {"name": "Notes",       "width": 24, "sample": "Check rubric"},
             ], "sample_rows": 12},
            {"name": "Grades",         "emoji": "🎯", "color": "10B981", "type": "table",
             "description": "Grade book: all subjects with weighted averages and GPA.",
             "columns": [
                 {"name": "Subject",     "width": 22, "sample": "Mathematics"},
                 {"name": "Credits",     "width": 10, "sample": "3"},
                 {"name": "Midterm",     "width": 12, "sample": "78"},
                 {"name": "Final",       "width": 12, "sample": "82"},
                 {"name": "GPA Points",  "width": 14, "formula": '=IF(E{ROW}>=90,4,IF(E{ROW}>=80,3,IF(E{ROW}>=70,2,1)))'},
                 {"name": "Letter",      "width": 12, "formula": '=IF(E{ROW}>=90,"A",IF(E{ROW}>=80,"B",IF(E{ROW}>=70,"C","D")))'},
             ], "sample_rows": 8},
            {"name": "Exams",          "emoji": "📅", "color": "EF4444", "type": "table",
             "description": "Exam schedule with countdown, topics to study, and results.",
             "columns": [
                 {"name": "Exam",       "width": 26, "sample": "Midterm — Math"},
                 {"name": "Subject",    "width": 18, "sample": "Mathematics"},
                 {"name": "Date",       "width": 14, "sample": "2024-03-15"},
                 {"name": "Status",     "width": 16, "dropdown": ["Upcoming","Studying","Done","Results In"]},
                 {"name": "Score",      "width": 12, "sample": "88"},
                 {"name": "Topics",     "width": 30, "sample": "Ch 1-5, Derivatives"},
             ], "sample_rows": 8},
            {"name": "Study Schedule", "emoji": "⏰", "color": "FBBF24", "type": "table",
             "description": "Weekly study sessions with subject, hours, and productivity rating.",
             "columns": [
                 {"name": "Date",       "width": 14, "sample": "2024-02-05"},
                 {"name": "Subject",    "width": 20, "sample": "Physics"},
                 {"name": "Hours",      "width": 10, "sample": "2"},
                 {"name": "Topic",      "width": 28, "sample": "Newton's Laws"},
                 {"name": "Rating",     "width": 14, "dropdown": ["⭐⭐⭐⭐⭐","⭐⭐⭐⭐","⭐⭐⭐","⭐⭐","⭐"]},
             ], "sample_rows": 12},
            {"name": "Goals",          "emoji": "🏆", "color": "F59E0B", "type": "table",
             "description": "Semester goals with deadlines and progress tracking.",
             "columns": [
                 {"name": "Goal",       "width": 30, "sample": "Get A in Math"},
                 {"name": "Deadline",   "width": 14, "sample": "2024-05-31"},
                 {"name": "Priority",   "width": 14, "dropdown": ["🔥 High","Medium","Low"]},
                 {"name": "Progress",   "width": 14, "dropdown": ["Not Started","In Progress","Almost Done","Done"]},
             ], "sample_rows": 6},
        ],
        "features": [
            "Auto GPA calculation from all subjects",
            "Assignment tracker with status and grade entry",
            "Exam countdown with topics checklist",
            "Weekly study hours tracker",
            "Semester goals with progress tracking",
            "Letter grade auto-calculation (A/B/C/D)",
            "Works for high school, college, and university",
            "No subscriptions — one-time purchase",
        ],
        "perfect_for": [
            "College and university students",
            "High school students preparing for exams",
            "Students managing multiple subjects",
            "Anyone who wants to improve their GPA",
            "Students with part-time jobs needing better time management",
            "Parents tracking their children's academic progress",
        ],
        "how_to_use": [
            "Add your subjects and credit hours to Grades tab",
            "Enter all assignments with due dates",
            "Log your study sessions weekly",
            "Dashboard shows GPA and pending work automatically",
        ],
        "tips": [
            "Log assignments immediately when your professor announces them.",
            "Set exam prep sessions 2 weeks before each exam.",
            "Rate your study sessions honestly — quality beats quantity.",
            "Review the dashboard every Sunday to plan the week.",
        ],
        "tags": [
            "student planner google sheets",
            "academic planner spreadsheet",
            "grade tracker template",
            "semester planner excel",
            "college planner template",
            "gpa calculator spreadsheet",
            "study schedule template",
            "assignment tracker google",
            "exam planner sheet",
            "student study planner",
            "homework tracker template",
            "college grade tracker",
            "student productivity sheet",
        ],
    },

    # ─── 5. Job Application Tracker ───────────────────────────────────
    {
        "slug": "job_application_tracker",
        "name": "Job Application Tracker",
        "subtitle": "Job Hunt Organizer & Interview Planner Google Sheets",
        "price": "$10",
        "listing_title": "Job Application Tracker Google Sheets | Job Hunt Organizer Interview Tracker | Career Spreadsheet",
        "listing_emoji": "💼",
        "category": "Craft Supplies & Tools → Templates → Spreadsheets",
        "description_intro": "Land your dream job faster. Track every application, interview, and follow-up in one organized spreadsheet.",
        "accent_color": "0EA5E9",
        "dark_color": "0F172A",
        "green_color": "22C55E",
        "yellow_color": "EAB308",
        "red_color": "EF4444",
        "kpis_preview": ["Applied", "Interviews", "Offers", "Response Rate"],
        "tabs": [
            {"name": "Dashboard",      "emoji": "🏠", "color": "0F172A", "type": "dashboard",
             "description": "Job search overview: applications, interviews, offers, response rate.",
             "kpis": [
                 {"label": "Applied",       "formula": "=COUNTA(Applications!A:A)-1"},
                 {"label": "Interviews",    "formula": "=COUNTIF(Applications!E:E,\"Interview\")"},
                 {"label": "Offers",        "formula": "=COUNTIF(Applications!E:E,\"Offer\")"},
                 {"label": "Response Rate", "formula": '=TEXT(B4/A4,"0%")'},
             ]},
            {"name": "Applications",   "emoji": "📋", "color": "0EA5E9", "type": "table",
             "description": "All job applications with company, role, date, status, and notes.",
             "columns": [
                 {"name": "Date Applied", "width": 14, "sample": "2024-01-15"},
                 {"name": "Company",      "width": 22, "sample": "Google"},
                 {"name": "Role",         "width": 26, "sample": "Product Manager"},
                 {"name": "Location",     "width": 18, "sample": "Remote"},
                 {"name": "Status",       "width": 18, "dropdown": ["Applied","Viewed","Phone Screen","Interview","Final Round","Offer","Rejected","Withdrawn","Ghosted"]},
                 {"name": "Salary Range", "width": 16, "sample": "$80k-$100k"},
                 {"name": "Source",       "width": 16, "dropdown": ["LinkedIn","Indeed","Company Site","Referral","Recruiter","Other"]},
                 {"name": "Notes",        "width": 30, "sample": "Applied via LinkedIn"},
             ], "sample_rows": 15},
            {"name": "Interviews",     "emoji": "🎤", "color": "22C55E", "type": "table",
             "description": "Interview tracker: date, type, interviewer, questions, outcome.",
             "columns": [
                 {"name": "Company",    "width": 22, "sample": "Google"},
                 {"name": "Date",       "width": 14, "sample": "2024-02-01"},
                 {"name": "Type",       "width": 18, "dropdown": ["Phone Screen","Video Call","Technical","On-Site","Panel","Case Study","Final"]},
                 {"name": "Outcome",    "width": 16, "dropdown": ["Passed","Rejected","Pending","Rescheduled"]},
                 {"name": "Questions",  "width": 40, "sample": "Tell me about yourself..."},
                 {"name": "Next Step",  "width": 24, "sample": "Technical interview in 1 week"},
             ], "sample_rows": 10},
            {"name": "Contacts",       "emoji": "👥", "color": "8B5CF6", "type": "table",
             "description": "Networking contacts, recruiters, and referrals.",
             "columns": [
                 {"name": "Name",       "width": 22, "sample": "Sarah Johnson"},
                 {"name": "Company",    "width": 22, "sample": "Meta"},
                 {"name": "Role",       "width": 22, "sample": "Engineering Manager"},
                 {"name": "Connection", "width": 18, "dropdown": ["Recruiter","Referral","Network","Alumni","LinkedIn"]},
                 {"name": "Last Touch", "width": 14, "sample": "2024-01-20"},
                 {"name": "Notes",      "width": 30, "sample": "Referred me to a PM role"},
             ], "sample_rows": 8},
            {"name": "Offers",         "emoji": "🎉", "color": "EAB308", "type": "table",
             "description": "Offer comparison: salary, benefits, equity, deadline.",
             "columns": [
                 {"name": "Company",    "width": 22, "sample": "Acme Corp"},
                 {"name": "Role",       "width": 24, "sample": "Product Manager"},
                 {"name": "Base $",     "width": 12, "sample": "90000"},
                 {"name": "Bonus $",    "width": 12, "sample": "10000"},
                 {"name": "Equity $",   "width": 12, "sample": "20000"},
                 {"name": "Total $",    "width": 14, "formula": "=D{ROW}+E{ROW}+F{ROW}"},
                 {"name": "Decision",   "width": 16, "dropdown": ["Pending","Accepted","Declined","Negotiating"]},
                 {"name": "Deadline",   "width": 14, "sample": "2024-02-15"},
             ], "sample_rows": 4},
            {"name": "Follow-ups",     "emoji": "📧", "color": "F97316", "type": "table",
             "description": "Schedule and track all follow-up emails and actions.",
             "columns": [
                 {"name": "Company",    "width": 22, "sample": "Google"},
                 {"name": "Action",     "width": 28, "sample": "Send thank you email"},
                 {"name": "Due Date",   "width": 14, "sample": "2024-02-03"},
                 {"name": "Done",       "width": 10, "dropdown": ["Yes","No"]},
                 {"name": "Notes",      "width": 28, "sample": "Emailed HR contact"},
             ], "sample_rows": 8},
        ],
        "features": [
            "Track unlimited job applications with full status history",
            "9 application statuses (Applied → Offer → Rejected)",
            "Interview tracker with questions and outcomes",
            "Offer comparison calculator (base + bonus + equity)",
            "Networking contacts and referrals database",
            "Follow-up email scheduler",
            "Response rate calculated automatically",
            "Works for any industry or career level",
        ],
        "perfect_for": [
            "Active job seekers managing multiple applications",
            "Recent graduates starting their job search",
            "Professionals looking for a career change",
            "Anyone applying to 10+ companies simultaneously",
            "People who want to track their job search ROI",
            "Career coaches organizing clients' job searches",
        ],
        "how_to_use": [
            "Log each application immediately after applying",
            "Update status when you hear back",
            "Add interviews to the Interviews tab with prep notes",
            "Compare offers side by side in the Offers tab",
        ],
        "tips": [
            "Follow up 5-7 days after applying if no response.",
            "Add interview questions you receive to prepare for next time.",
            "Always log the recruiter name in Contacts for future reference.",
            "Never apply to more than 10 companies per day — quality over quantity.",
        ],
        "tags": [
            "job application tracker",
            "job hunt spreadsheet",
            "job search organizer",
            "interview tracker google sheets",
            "job application google sheets",
            "career tracker template",
            "job offer comparison sheet",
            "job search planner",
            "application status tracker",
            "job hunting template excel",
            "networking tracker sheet",
            "interview prep spreadsheet",
            "job search dashboard",
        ],
    },

]
